version: '3'

services:
  app:
    image: lab-agent
    deploy:
      replicas: 3
    ports:
      - 8081-8083
      - 3301-3303
  ansible:
    build:
      context: ./ansible
    volumes:
      - ./ansible/playbooks:/playbooks
      - ./ansible/inventory:/inventory
      - ./ansible/ansible.cfg:/etc/ansible/ansible.cfg
    depends_on:
      - app
    ports:
      - "8085:8080"
    expose:
      - 5000